In [1]:
train_A1 = [5,5.11,5.6,5.9,4.8,5.8,5.3,5.8,5.5,5.6]
train_A2 = [45,26,30,34,40,36,19,28,23,32]
label = ['H','L','M','M','H','M','L','M','L','M']
weight = [77,47,55,59,72,60,40,60,45,58]
# cho điểm test 
test_a1=5.5
test_a2=38
print(len(train_A1))
print(len(train_A2))
print(len(label))
print(len(weight))

10
10
10
10


In [2]:
import math
# Euclidean
def get_dis(test_a1,test_a2,train_A1,train_A2):
    dis = []
    for i in range(len(train_A1)):
        d = (train_A1[i] - test_a1)**2 + (train_A2[i] - test_a2)**2
        dis.append(math.sqrt(d))
    return dis
print(get_dis(test_a1,test_a2,train_A1,train_A2))


[7.0178344238090995, 12.006335827387138, 8.000624975587845, 4.019950248448356, 2.118962010041709, 2.0223748416156684, 19.001052602421794, 10.004498987955369, 15.0, 6.000833275470999]


In [3]:
# Manhattan
def get_dis(test_a1,test_a2,train_A1,train_A2):
    dis = []
    for i in range(len(train_A1)):
        d = abs(train_A1[i] - test_a1) + abs(train_A2[i] - test_a2)
        dis.append(d)
    return dis
print(get_dis(test_a1,test_a2,train_A1,train_A2))


[7.5, 12.39, 8.1, 4.4, 2.7, 2.3, 19.2, 10.3, 15.0, 6.1]


In [4]:
d = get_dis(test_a1,test_a2,train_A1,train_A2)
for i in range(len(d)):
    print(d[i],end = " ")
    print(label[i])


7.5 H
12.39 L
8.1 M
4.4 M
2.7 H
2.3 M
19.2 L
10.3 M
15.0 L
6.1 M


In [5]:
import numpy as np
index = np.argsort(d)
print(index)
k = 3
k_index = index[:k]
print(k_index)
for i in k_index:
    print(label[i])

[5 4 3 9 0 2 7 1 8 6]
[5 4 3]
M
H
M


In [6]:
index = np.argsort(d)
print(index)
k = 3
k_index = index[:k]
print(k_index)
res = 0 
for i in k_index:
    res += weight[i]
print(res/3)


[5 4 3 9 0 2 7 1 8 6]
[5 4 3]
63.666666666666664


In [7]:
a = np.array([1,2,5,7])
a1 = np.array([[1,2,3],[5,6,7]])
a2 = np.array([[7,8,9],[10,11,12]])

a = np.array([[[1,2,3],[5,6,7]],[[7,8,9],[10,11,12]]])
print(a)



[[[ 1  2  3]
  [ 5  6  7]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
# K-NN
# K-NN giải quyết các bài toán phức tạp
# K-NN có độ chính xác khác cao
# Dự đoán kết quả của dữ liệu mới đơn giản
# Rất rủi ro khi K nhỏ